/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as RegistryDotjsonRouteImport } from './routes/registry[.]json'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as RChar123itemIdChar125DotjsonRouteImport } from './routes/r/{$itemId}[.]json'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTableRouteImport } from './routes/components/table'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsShimmeringTextRouteImport } from './routes/components/shimmering-text'
import { Route as ComponentsSheetRouteImport } from './routes/components/sheet'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsScrollAreaRouteImport } from './routes/components/scroll-area'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsProgressRouteImport } from './routes/components/progress'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsPaginationRouteImport } from './routes/components/pagination'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsFieldRouteImport } from './routes/components/field'
import { Route as ComponentsDropdownMenuRouteImport } from './routes/components/dropdown-menu'
import { Route as ComponentsDrawerRouteImport } from './routes/components/drawer'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsComboboxRouteImport } from './routes/components/combobox'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsChartsRouteImport } from './routes/components/charts'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBreadcrumbRouteImport } from './routes/components/breadcrumb'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsAudioPlayerRouteImport } from './routes/components/audio-player'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryDotjsonRoute = RegistryDotjsonRouteImport.update({
  id: '/registry.json',
  path: '/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const RChar123itemIdChar125DotjsonRoute =
  RChar123itemIdChar125DotjsonRouteImport.update({
    id: '/r/{$itemId}.json',
    path: '/r/{$itemId}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/components/textarea',
  path: '/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/components/table',
  path: '/components/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/components/spinner',
  path: '/components/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsShimmeringTextRoute =
  ComponentsShimmeringTextRouteImport.update({
    id: '/components/shimmering-text',
    path: '/components/shimmering-text',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSheetRoute = ComponentsSheetRouteImport.update({
  id: '/components/sheet',
  path: '/components/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/components/separator',
  path: '/components/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsScrollAreaRoute = ComponentsScrollAreaRouteImport.update({
  id: '/components/scroll-area',
  path: '/components/scroll-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/components/radio-group',
  path: '/components/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsProgressRoute = ComponentsProgressRouteImport.update({
  id: '/components/progress',
  path: '/components/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/components/popover',
  path: '/components/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPaginationRoute = ComponentsPaginationRouteImport.update({
  id: '/components/pagination',
  path: '/components/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFieldRoute = ComponentsFieldRouteImport.update({
  id: '/components/field',
  path: '/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropdownMenuRoute = ComponentsDropdownMenuRouteImport.update({
  id: '/components/dropdown-menu',
  path: '/components/dropdown-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDrawerRoute = ComponentsDrawerRouteImport.update({
  id: '/components/drawer',
  path: '/components/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/components/dialog',
  path: '/components/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/components/date-picker',
  path: '/components/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/components/command',
  path: '/components/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComboboxRoute = ComponentsComboboxRouteImport.update({
  id: '/components/combobox',
  path: '/components/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChartsRoute = ComponentsChartsRouteImport.update({
  id: '/components/charts',
  path: '/components/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBreadcrumbRoute = ComponentsBreadcrumbRouteImport.update({
  id: '/components/breadcrumb',
  path: '/components/breadcrumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/components/avatar',
  path: '/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAudioPlayerRoute = ComponentsAudioPlayerRouteImport.update({
  id: '/components/audio-player',
  path: '/components/audio-player',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/components/alert',
  path: '/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/colors': typeof ColorsRoute
  '/integrate': typeof IntegrateRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/typography': typeof TypographyRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/audio-player': typeof ComponentsAudioPlayerRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/charts': typeof ComponentsChartsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/shimmering-text': typeof ComponentsShimmeringTextRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/r/{$itemId}.json': typeof RChar123itemIdChar125DotjsonRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/colors': typeof ColorsRoute
  '/integrate': typeof IntegrateRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/typography': typeof TypographyRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/audio-player': typeof ComponentsAudioPlayerRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/charts': typeof ComponentsChartsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/shimmering-text': typeof ComponentsShimmeringTextRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/r/{$itemId}.json': typeof RChar123itemIdChar125DotjsonRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/colors': typeof ColorsRoute
  '/integrate': typeof IntegrateRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/typography': typeof TypographyRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/audio-player': typeof ComponentsAudioPlayerRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/charts': typeof ComponentsChartsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/shimmering-text': typeof ComponentsShimmeringTextRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/r/{$itemId}.json': typeof RChar123itemIdChar125DotjsonRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/colors'
    | '/integrate'
    | '/registry.json'
    | '/typography'
    | '/components/accordion'
    | '/components/alert'
    | '/components/audio-player'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/charts'
    | '/components/checkbox'
    | '/components/combobox'
    | '/components/command'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/input'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/scroll-area'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/shimmering-text'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/tooltip'
    | '/r/{$itemId}.json'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/colors'
    | '/integrate'
    | '/registry.json'
    | '/typography'
    | '/components/accordion'
    | '/components/alert'
    | '/components/audio-player'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/charts'
    | '/components/checkbox'
    | '/components/combobox'
    | '/components/command'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/input'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/scroll-area'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/shimmering-text'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/tooltip'
    | '/r/{$itemId}.json'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/colors'
    | '/integrate'
    | '/registry.json'
    | '/typography'
    | '/components/accordion'
    | '/components/alert'
    | '/components/audio-player'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/charts'
    | '/components/checkbox'
    | '/components/combobox'
    | '/components/command'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/input'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/scroll-area'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/shimmering-text'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/tooltip'
    | '/r/{$itemId}.json'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  ColorsRoute: typeof ColorsRoute
  IntegrateRoute: typeof IntegrateRoute
  RegistryDotjsonRoute: typeof RegistryDotjsonRoute
  TypographyRoute: typeof TypographyRoute
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAudioPlayerRoute: typeof ComponentsAudioPlayerRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBreadcrumbRoute: typeof ComponentsBreadcrumbRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsChartsRoute: typeof ComponentsChartsRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsComboboxRoute: typeof ComponentsComboboxRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDrawerRoute: typeof ComponentsDrawerRoute
  ComponentsDropdownMenuRoute: typeof ComponentsDropdownMenuRoute
  ComponentsFieldRoute: typeof ComponentsFieldRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsPaginationRoute: typeof ComponentsPaginationRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsProgressRoute: typeof ComponentsProgressRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsScrollAreaRoute: typeof ComponentsScrollAreaRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSheetRoute: typeof ComponentsSheetRoute
  ComponentsShimmeringTextRoute: typeof ComponentsShimmeringTextRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  RChar123itemIdChar125DotjsonRoute: typeof RChar123itemIdChar125DotjsonRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry.json': {
      id: '/registry.json'
      path: '/registry.json'
      fullPath: '/registry.json'
      preLoaderRoute: typeof RegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/{$itemId}.json': {
      id: '/r/{$itemId}.json'
      path: '/r/{$itemId}.json'
      fullPath: '/r/{$itemId}.json'
      preLoaderRoute: typeof RChar123itemIdChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/components/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/table': {
      id: '/components/table'
      path: '/components/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/components/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/shimmering-text': {
      id: '/components/shimmering-text'
      path: '/components/shimmering-text'
      fullPath: '/components/shimmering-text'
      preLoaderRoute: typeof ComponentsShimmeringTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sheet': {
      id: '/components/sheet'
      path: '/components/sheet'
      fullPath: '/components/sheet'
      preLoaderRoute: typeof ComponentsSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/components/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/scroll-area': {
      id: '/components/scroll-area'
      path: '/components/scroll-area'
      fullPath: '/components/scroll-area'
      preLoaderRoute: typeof ComponentsScrollAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/components/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/components/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/pagination': {
      id: '/components/pagination'
      path: '/components/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/field': {
      id: '/components/field'
      path: '/components/field'
      fullPath: '/components/field'
      preLoaderRoute: typeof ComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropdown-menu': {
      id: '/components/dropdown-menu'
      path: '/components/dropdown-menu'
      fullPath: '/components/dropdown-menu'
      preLoaderRoute: typeof ComponentsDropdownMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/drawer': {
      id: '/components/drawer'
      path: '/components/drawer'
      fullPath: '/components/drawer'
      preLoaderRoute: typeof ComponentsDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/components/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/command': {
      id: '/components/command'
      path: '/components/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/combobox': {
      id: '/components/combobox'
      path: '/components/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/charts': {
      id: '/components/charts'
      path: '/components/charts'
      fullPath: '/components/charts'
      preLoaderRoute: typeof ComponentsChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/breadcrumb': {
      id: '/components/breadcrumb'
      path: '/components/breadcrumb'
      fullPath: '/components/breadcrumb'
      preLoaderRoute: typeof ComponentsBreadcrumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/components/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/audio-player': {
      id: '/components/audio-player'
      path: '/components/audio-player'
      fullPath: '/components/audio-player'
      preLoaderRoute: typeof ComponentsAudioPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/components/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  ColorsRoute: ColorsRoute,
  IntegrateRoute: IntegrateRoute,
  RegistryDotjsonRoute: RegistryDotjsonRoute,
  TypographyRoute: TypographyRoute,
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAudioPlayerRoute: ComponentsAudioPlayerRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBreadcrumbRoute: ComponentsBreadcrumbRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsChartsRoute: ComponentsChartsRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsComboboxRoute: ComponentsComboboxRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDrawerRoute: ComponentsDrawerRoute,
  ComponentsDropdownMenuRoute: ComponentsDropdownMenuRoute,
  ComponentsFieldRoute: ComponentsFieldRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsPaginationRoute: ComponentsPaginationRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsProgressRoute: ComponentsProgressRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsScrollAreaRoute: ComponentsScrollAreaRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSheetRoute: ComponentsSheetRoute,
  ComponentsShimmeringTextRoute: ComponentsShimmeringTextRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  RChar123itemIdChar125DotjsonRoute: RChar123itemIdChar125DotjsonRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
